---
title: "Gapminder Exercise Template"
author: "Mine Cetinkaya-Rundel"
date: "8/21/2015"
output: html_document
---

## Load packages

Load the following packages for 

- data wrangling (`dplyr`), and 
- data visualizaiton (`ggplot2`)

```{r message=FALSE}
library(dplyr)
library(ggplot2)
```

## Load data

```{r}
gap <- read.csv("https://bit.ly/gap_data")
```

## Exercises

### Exercise 1

How many observations are in this dataset?

```{r nrow}
str(gap)
dim(gap)
```

### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.

```{r eu_52}
euro <- filter(gap,continent == "Europe" & year==1952)
plot(euro$gdpPercap~euro$lifeExp,xlab = "Life Expectancy",ylab="GDP")
ggplot(euro)+geom_point(data=euro,aes(x=gdpPercap,y=lifeExp))
```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67}
eu_52_67 <- gap %>% filter(continent == "Europe" & year %in% c(1952,1967))
ggplot(data=eu_52_67,aes(x=gdpPercap,y=lifeExp,color=factor(year))) + geom_point()
```

